runtime: python312

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /sounds
  static_dir: sounds

- url: /
  static_files: index.html
  upload: index.html

- url: /(.*)
  static_files: \1
  upload: .*
